2024-08-20 16:01:19,143 ERROR: Exception on /signup [POST] [in C:\Users\gts\Desktop\flask\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\gts\Desktop\flask\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gts\Desktop\flask\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gts\Desktop\flask\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gts\Desktop\flask\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gts\Desktop\flask\app.py", line 63, in signup
    form = SignUpForm()
           ^^^^^^^^^^^^
  File "C:\Users\gts\Desktop\flask\venv\Lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gts\Desktop\flask\venv\Lib\site-packages\flask_wtf\form.py", line 73, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "C:\Users\gts\Desktop\flask\venv\Lib\site-packages\wtforms\form.py", line 286, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "C:\Users\gts\Desktop\flask\venv\Lib\site-packages\wtforms\form.py", line 127, in process
    field.process(formdata, data, extra_filters=field_extra_filters)
  File "C:\Users\gts\Desktop\flask\venv\Lib\site-packages\wtforms\csrf\core.py", line 44, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gts\Desktop\flask\venv\Lib\site-packages\flask_wtf\csrf.py", line 147, in generate_csrf_token
    return generate_csrf(
           ^^^^^^^^^^^^^^
  File "C:\Users\gts\Desktop\flask\venv\Lib\site-packages\flask_wtf\csrf.py", line 36, in generate_csrf
    secret_key = _get_config(
                 ^^^^^^^^^^^^
  File "C:\Users\gts\Desktop\flask\venv\Lib\site-packages\flask_wtf\csrf.py", line 136, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
